"""
SIPETA TPK - Seminar Proposal PPT Generator (Part 1: Slide Data)
Generates slides data structure for the presentation.
"""

SLIDES = [
    {
        "title": "SEMINAR PROPOSAL SKRIPSI",
        "subtitle": "Rancang Bangun Website Sistem Informasi Geografis (SIG)\nInventarisasi dan Pemetaan Stok Kayu Jati di TPK Cabak\nBerbasis Metode Web Development Life Cycle (WDLC)",
        "content": [
            "Disusun Oleh:",
            "Yolan Ibnu Prasetya — 1222002009",
            "",
            "Dosen Pembimbing:",
            "Zakiul Fahmi Jailani, S.Kom.",
            "",
            "PROGRAM STUDI SISTEM INFORMASI",
            "FAKULTAS TEKNIK DAN ILMU KOMPUTER",
            "UNIVERSITAS BAKRIE — 2026"
        ],
        "layout": "cover"
    },
    {
        "title": "OUTLINE PRESENTASI",
        "subtitle": "",
        "content": [
            "1. Latar Belakang Masalah",
            "2. Identifikasi & Rumusan Masalah",
            "3. Batasan & Tujuan Penelitian",
            "4. Landasan Teori: SIG & WebGIS",
            "5. Landasan Teori: Tech Stack",
            "6. Penelitian Terdahulu & Research Gap",
            "7. Metodologi: Pengumpulan Data",
            "8. Metodologi: 6 Tahap WDLC",
            "9. Rancangan Sistem: Fitur & Peran",
            "10. Profil Objek Penelitian",
            "11. Struktur Organisasi TPK Cabak",
            "12. Rencana Pengujian: SUS",
            "13. Manfaat Penelitian",
            "14. Kesimpulan & Kontribusi",
            "15. Penutup"
        ],
        "layout": "content"
    },
    {
        "title": "LATAR BELAKANG MASALAH",
        "subtitle": "",
        "content": [
            "■ TPK Cabak, Kec. Jiken, Kab. Blora — area 9,7 Ha, 15 blok kaveling (A–I)",
            "■ Kayu jati dengan 3 klasifikasi grade: AI, AII, AIII",
            "",
            "4 Permasalahan Utama:",
            "❶ Pencatatan stok masih MANUAL (buku besar & spreadsheet)",
            "    → Rentan human error, duplikasi, dan manipulasi data",
            "❷ Tidak ada PETA DIGITAL kaveling",
            "    → Petugas kesulitan menemukan tumpukan kayu di area 9,7 Ha",
            "❸ LAG INFORMASI antara lapangan & manajemen",
            "    → Data yang diterima Kepala TPK bisa sudah kadaluarsa",
            "❹ Keterbatasan SISHK (Sistem Informasi Hasil Kayu Perhutani)",
            "    → Hanya tabular, tidak ada fitur peta/pelacakan spasial",
        ],
        "layout": "content"
    },
    {
        "title": "IDENTIFIKASI & RUMUSAN MASALAH",
        "subtitle": "",
        "content": [
            "IDENTIFIKASI MASALAH:",
            "1. Pencatatan inventaris stok kayu masih manual → rentan kesalahan",
            "2. Ketiadaan visualisasi peta digital terintegrasi dengan data inventaris",
            "3. Lag informasi antara kondisi riil lapangan & data manajemen",
            "",
            "RUMUSAN MASALAH (Research Questions):",
            "RQ1: Bagaimana merancang & membangun Website SIG Inventarisasi",
            "         dan Pemetaan Stok Kayu Jati menggunakan Metode WDLC?",
            "RQ2: Bagaimana memvisualisasikan letak & status kaveling pada",
            "         peta interaktif WebGIS?",
            "RQ3: Bagaimana merancang pembagian hak akses (role) pengguna?",
            "RQ4: Bagaimana tingkat usability sistem yang dibangun (diukur SUS)?",
        ],
        "layout": "content"
    },
    {
        "title": "BATASAN & TUJUAN PENELITIAN",
        "subtitle": "",
        "content": [
            "BATASAN MASALAH:",
            "1. Objek: TPK Cabak, Kec. Jiken, Kab. Blora (kayu jati)",
            "2. Frontend: Next.js + React.js",
            "3. Pemetaan: Leaflet.js (marker & polygon GeoJSON)",
            "4. Database: Supabase (PostgreSQL) + Realtime WebSocket",
            "5. Scope: Inventarisasi & pemetaan (bukan transaksi keuangan)",
            "",
            "TUJUAN PENELITIAN:",
            "T1: Merancang & membangun Website SIG menggunakan WDLC",
            "T2: Memvisualisasikan letak & status kaveling pada peta interaktif",
            "T3: Merancang pembagian hak akses Admin dan Staff",
            "T4: Mengukur tingkat usability sistem menggunakan SUS",
        ],
        "layout": "content"
    },
    {
        "title": "LANDASAN TEORI: KONSEP SIG & WebGIS",
        "subtitle": "",
        "content": [
            "SISTEM INFORMASI GEOGRAFIS (SIG):",
            "• Kerangka teknologi untuk mengakuisisi, menyimpan, memanipulasi,",
            "  dan memvisualisasikan data bereferensi koordinat spasial",
            "• Memadukan data geometri (titik, garis, poligon) dengan atribut deskriptif",
            "  (Surachman, 2024)",
            "",
            "WebGIS:",
            "• Sistem pemetaan interaktif yang diakses via browser web",
            "• Mengeliminasi kebutuhan instalasi software GIS berat (Ate et al., 2024)",
            "",
            "SIPETA TPK = SIG + Inventarisasi dalam satu platform WebGIS",
            "• Data geometri → batas fisik blok kaveling TPK Cabak",
            "• Data atribut → stok kayu jati (jenis, grade, volume) per kaveling",
        ],
        "layout": "content"
    },
    {
        "title": "LANDASAN TEORI: TECH STACK",
        "subtitle": "",
        "content": [
            "FRONTEND:",
            "• Next.js — SSR untuk waktu muat cepat (Hanafi et al., 2024)",
            "• React.js — Komponen UI reaktif & modular (Fathir Rachman et al., 2023)",
            "• TypeScript — Static type-checking untuk keandalan kode",
            "• Tailwind CSS — Desain responsif di semua perangkat",
            "",
            "PEMETAAN:",
            "• Leaflet.js — Peta interaktif, marker, polygon (Uzlah et al., 2025)",
            "• GeoJSON — Format standar data spasial (Mauliza et al., 2022)",
            "• QGIS — Digitasi batas kaveling → ekspor GeoJSON",
            "",
            "BACKEND & DATABASE:",
            "• Supabase (BaaS) — Auth, Realtime WebSocket, RLS (Nugraha et al., 2026)",
            "• PostgreSQL — Database enterprise-grade, JSONB support",
        ],
        "layout": "content"
    },
    {
        "title": "PENELITIAN TERDAHULU & RESEARCH GAP",
        "subtitle": "",
        "content": [
            "No | Peneliti (Tahun)              | Hasil                    | Gap",
            "1  | Agustine & Handayani (2025)    | Inventaris kayu web      | Tidak ada WebGIS",
            "2  | Okyusmarianto et al. (2024)    | WebGIS evaluasi lahan    | Tidak ada inventaris",
            "3  | Nugraha et al. (2026)          | React + Supabase RT      | Tidak ada SIG/peta",
            "4  | Aprilisa & Aulia (2024)        | WDLC efektif             | Tidak ada tech modern",
            "5  | Ramadhan et al. (2022)         | QGIS pemetaan poligon    | Objek statis",
            "",
            "RESEARCH GAP:",
            "Belum ada penelitian yang MENGGABUNGKAN:",
            "✓ Inventarisasi kayu + WebGIS real-time",
            "✓ Tech stack modern (Next.js + Supabase)",
            "✓ Metode WDLC",
            "→ Penelitian ini MENGISI celah tersebut secara komprehensif",
        ],
        "layout": "content"
    },
    {
        "title": "METODOLOGI: PENGUMPULAN DATA",
        "subtitle": "Pendekatan: Research and Development (R&D)",
        "content": [
            "1. OBSERVASI LANGSUNG",
            "   • Kunjungan ke TPK Cabak, Kec. Jiken, Kab. Blora",
            "   • Mengamati proses pencatatan stok & tata letak kaveling",
            "",
            "2. WAWANCARA SEMI-TERSTRUKTUR",
            "   • Narasumber: Kepala TPK (Bp. Purwanto) & staf lapangan",
            "   • Menggali kebutuhan fungsional & non-fungsional sistem",
            "",
            "3. STUDI DOKUMEN",
            "   • Kajian catatan stok manual (buku besar & spreadsheet)",
            "   • Kajian jurnal ilmiah nasional & internasional",
            "",
            "Bukti: Surat Izin Penelitian No. 151/KPH/CBK/IV/2026",
        ],
        "layout": "content"
    },
    {
        "title": "METODOLOGI: 6 TAHAP WDLC",
        "subtitle": "Web Development Life Cycle",
        "content": [
            "1. PLANNING → Ruang lingkup, target pengguna, tech stack",
            "2. ANALYSIS → Kebutuhan fungsional & non-fungsional",
            "3. DESIGN → Flowchart, UML, ERD, Wireframe",
            "4. DEVELOPMENT → Coding: Next.js, Leaflet, Supabase",
            "5. TESTING → Usability Testing dengan SUS (skor ≥ 68)",
            "6. DEPLOYMENT → Hosting di Netlify + CD dari GitHub",
            "",
            "MEKANISME ITERASI:",
            "Jika skor SUS < 68 → kembali ke tahap Design/Development",
            "→ Perbaikan dilakukan → Testing diulang",
            "→ Ini yang membedakan WDLC dari Waterfall tradisional",
            "",
            "(Aprilisa & Aulia, 2024; Asfari, 2024)",
        ],
        "layout": "content"
    },
    {
        "title": "RANCANGAN SISTEM: FITUR & PERAN PENGGUNA",
        "subtitle": "",
        "content": [
            "ADMIN (Kepala TPK):",
            "• Dashboard statistik (total stok & pergerakan kayu)",
            "• Peta WebGIS interaktif semua blok (A–I)",
            "• Manajemen inventaris (input, edit, hapus data kayu)",
            "• Manajemen akun Staff",
            "• Unduh laporan (PDF/CSV)",
            "• Log histori perubahan data",
            "",
            "STAFF (Petugas Lapangan):",
            "• Peta kaveling real-time (read-only)",
            "• Input data kayu masuk (jenis, grade, volume)",
            "• Pencatatan mutasi lokasi antar kaveling",
            "• Akses dibatasi oleh Row Level Security (RLS)",
            "",
            "Semua fitur diakses via browser (laptop/smartphone)",
        ],
        "layout": "content"
    },
    {
        "title": "PROFIL OBJEK PENELITIAN: TPK CABAK",
        "subtitle": "",
        "content": [
            "■ Nama: Tempat Penimbunan Kayu (TPK) Cabak",
            "■ Alamat: Jl. Cabak–Nglobo Km 0,7, Ds. Cabak, Kec. Jiken,",
            "  Kab. Blora, Jawa Tengah",
            "■ Di bawah: KPH Cepu, Divisi Regional Jateng, Perum Perhutani",
            "■ Luas area: ± 9,7 hektar, 15 blok kaveling (A–I)",
            "",
            "Alur Operasional Kayu:",
            "Kayu masuk → Pengukuran kubikasi → Klasifikasi grade (AI/AII/AIII)",
            "→ Penomoran & barcode → Pencatatan administrasi SISHK",
            "→ Penempatan ke blok kaveling → Distribusi/penjualan",
            "",
            "Izin Penelitian: No. 151/KPH/CBK/IV/2026",
            "dari Kepala TPK — Bapak Purwanto",
        ],
        "layout": "content"
    },
    {
        "title": "STRUKTUR ORGANISASI TPK CABAK",
        "subtitle": "",
        "content": [
            "Kepala TPK (Bp. Purwanto) ← ADMIN SIPETA",
            "├── Penguji (Bp. Mustamarin & Mautono)",
            "├── Mandor Penyerahan",
            "├── SP TU Keuangan",
            "├── Operator SISHK ← STAFF SIPETA",
            "├── Operator Komputer ← STAFF SIPETA",
            "├── Mandor Penerimaan ← STAFF SIPETA",
            "├── Mandor Barcode ← STAFF SIPETA",
            "├── Mandor AI ← STAFF SIPETA",
            "├── Mandor AII ← STAFF SIPETA",
            "├── Mandor AIII",
            "├── Mandor Angkutan",
            "└── Penjaga",
            "",
            "Total Responden SUS: 7 orang (Sampling Jenuh/Sensus)",
        ],
        "layout": "content"
    },
    {
        "title": "RENCANA PENGUJIAN: SYSTEM USABILITY SCALE (SUS)",
        "subtitle": "",
        "content": [
            "■ Instrumen: Kuesioner SUS (John Brooke) — 10 pernyataan, skala 1–5",
            "■ Responden: 7 orang (2 Admin + 5 Staff) — Sampling Jenuh",
            "",
            "Rumus SUS per responden:",
            "Skor = {(Q1-1)+(5-Q2)+(Q3-1)+(5-Q4)+(Q5-1)+(5-Q6)",
            "       +(Q7-1)+(5-Q8)+(Q9-1)+(5-Q10)} × 2,5",
            "",
            "Grade SUS:",
            "84,1–100 → Grade A (Best Imaginable) — Acceptable",
            "72,6–78,8 → Grade B (Excellent) — Acceptable",
            "62,6–71,0 → Grade C (Good) — Acceptable",
            "38,9–62,6 → Grade D (Ok) — Marginal",
            "",
            "Ambang batas keberhasilan: Skor rata-rata ≥ 68 (Acceptable)",
        ],
        "layout": "content"
    },
    {
        "title": "MANFAAT PENELITIAN",
        "subtitle": "",
        "content": [
            "MANFAAT TEORITIS:",
            "• Memperkaya keilmuan SIG & integrasi inventaris kehutanan",
            "  dengan pemetaan spasial berbasis modern web stack",
            "• Referensi akademis: efektivitas Supabase Realtime + WDLC",
            "• Data empiris SUS pada WebGIS kehutanan Indonesia",
            "",
            "MANFAAT PRAKTIS:",
            "• Bagi TPK Cabak: Mempermudah administrasi, mempercepat",
            "  pencarian lokasi kayu, meningkatkan akurasi laporan stok",
            "• Bagi Petugas: Pengelolaan data efisien via smartphone,",
            "  mengurangi beban pencatatan manual, transparansi",
            "• Bagi Penulis: Implementasi ilmu perkuliahan & kontribusi",
            "  dalam digitalisasi sektor kehutanan nasional",
        ],
        "layout": "content"
    },
    {
        "title": "KESIMPULAN & KONTRIBUSI",
        "subtitle": "",
        "content": [
            "1. SOLUSI WebGIS TERINTEGRASI",
            "   → Peta Leaflet.js + inventaris kayu jati real-time",
            "   → Mengisi keterbatasan SISHK yang hanya tabular",
            "",
            "2. TEKNOLOGI WEB MODERN",
            "   → Next.js + Supabase + Leaflet = cepat, aman, skalabel",
            "   → Data tersinkron real-time via WebSocket",
            "",
            "3. METODE WDLC TERSTRUKTUR",
            "   → Pengembangan iteratif berbasis kebutuhan pengguna nyata",
            "",
            "4. VALIDASI USABILITY EMPIRIS",
            "   → Pengujian SUS dengan 7 responden sampling jenuh",
            "   → Memastikan sistem diterima pengguna secara kuantitatif",
        ],
        "layout": "content"
    },
    {
        "title": "TERIMA KASIH",
        "subtitle": "Sesi Tanya Jawab",
        "content": [
            "Yolan Ibnu Prasetya",
            "1222002009",
            "",
            "Program Studi Sistem Informasi",
            "Fakultas Teknik dan Ilmu Komputer",
            "Universitas Bakrie",
            "",
            "Dosen Pembimbing:",
            "Zakiul Fahmi Jailani, S.Kom.",
            "",
            "Wassalamualaikum Warahmatullahi Wabarakatuh",
        ],
        "layout": "cover"
    },
]

if __name__ == "__main__":
    print(f"Total slides: {len(SLIDES)}")
    for i, s in enumerate(SLIDES):
        print(f"  Slide {i+1}: {s['title']}")
